### ISSUE TITLE
[BUG] Configure Skills Not Working Properly

### ISSUE THREAD

**Issue by pwykersotz** [Larkinabout/fvtt-custom-dnd5e#107]
Configure skills is no longer working (custom-dnd5e and lib wrapper are the only modules enabled)

Name changes function, but altered skills no longer sort alphabetically by name.
![image](https://github.com/user-attachments/assets/50bcdf0a-3b8b-42e7-8cd2-11077a36ea3b)
![image](https://github.com/user-attachments/assets/feecf766-eea1-49b6-b70e-35e905cc1431)

New skills do not display despite being enabled.
![image](https://github.com/user-attachments/assets/b05d7166-705a-4c74-a1d4-e7578c415add)
![image](https://github.com/user-attachments/assets/1a106500-f91d-41dd-9d61-254c26d4c824)

Ability changes to skills do not propagate to character sheet.
![image](https://github.com/user-attachments/assets/77b7e376-18d1-448a-88a7-fbf108791fd5)
![image](https://github.com/user-attachments/assets/7d1ee18d-d15a-4402-babd-dcf1c5e1c3a3)

**Module Data**
[custom-dnd5e.json](https://github.com/user-attachments/files/17059538/custom-dnd5e.json)

No errors appear to be generated.

**Versions:**
- Module: [1.0.2]
- System: [dnd5e 4.0.2]
- Foundry VTT: [12.331]
- Browser: [Brave Version 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)](https://brave.com/latest/)]

**Comment by Larkinabout** [comment]
> Name changes function, but altered skills no longer sort alphabetically by name.
The order on the character sheet is determined by the order in the Configure Skills list. As as I remember, it's always been this way, unless dnd5e was doing it's own sorting.

> New skills do not display despite being enabled.
This one is a bug and I'll fix it for the next release. It's happened because I moved when the abilities and skills configs are updated.

> Ability changes to skills do not propagate to character sheet.
It looks like something has changed with the dnd5e system as it now stores each skills ability against the actor and uses that instead. It means setting it in the config no longer does anything for existing actors. Creating new actors does show the correct skill ability based on the config. I'll probably need to add a macro to allow users to overwrite every actors skills abilities with the ones from the config. Fun!

**Comment by pwykersotz** [comment]
> The order on the character sheet is determined by the order in the Configure Skills list. As far as I remember, it's always been this way, unless dnd5e was doing it's own sorting.

Huh, you're right. I somehow it was auto sorting on previous versions (before 4.0), but if I manually move it, it's just fine. Thanks!

And thanks for the update and continued support. This module is fantastic.
