### ISSUE TITLE
Define Skill Tag

### ISSUE THREAD

**Issue by gogrady4117** [Larkinabout/fvtt-custom-dnd5e#55]
Currently adding new Skills to the character sheet generates a random ID tag for the skill. It would be nice to be able to define these within the new skill creation in order to call upon those skills more easily within macros, chat, or nested journal commands. 

**Versions**
- Module: 0.6.0
- System: [dnd5e 3.0.3]
- Foundry VTT: [11.315]

**Comment by kaelad02** [comment]
I was trying to help on Discord so they could create a roll button in a journal, either manually or with the system's enricher. For example, if you create a new skill named Technology, I want to be able to use it like:

- `[[/r 1d20 + @skills.technology.total]]`
- `[[/skill technology]]`

But from what I could tell, the module generates a random ID instead of exposing the `key` or `fullKey` for a new skill. Even if you don't expose it, what if you just slugify the label the user gives.

**Comment by Larkinabout** [comment]
I've exposed the key in another place for the same purpose, so I can do the same here. As a current workaround, you can export the data using the option in the module's Debug Settings menu, open the file in a notepad app, replace the key (it should be in two places), save and reimport the file.

**Comment by Larkinabout** [comment]
Added in 0.12.2.
